/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.*; 
import javax.swing.*;
/**
 *
 * @author DIALLO Mamoudou 
 */
public class InitDlg extends javax.swing.JDialog {

    //Attributs
    private int nc;
    private LesJoueurs lj;
    private boolean ok;

    
    
    public InitDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.nc = 4;
        this.lj= new LesJoueurs();
        this.ok = false;
    }
    
    //Accesseurs
    public int getNiveau()
    {
        return this.nc;
    }
    public LesJoueurs getJoueurs()
    {
        return this.lj; 
    }
    public boolean getOk()
    {
        return this.ok;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        gauche = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        enfant = new javax.swing.JRadioButton();
        debutant = new javax.swing.JRadioButton();
        avance = new javax.swing.JRadioButton();
        expert = new javax.swing.JRadioButton();
        droite = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lara = new javax.swing.JCheckBox();
        jack = new javax.swing.JCheckBox();
        jean = new javax.swing.JCheckBox();
        amadeus = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();
        BPhoto = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Annuler = new javax.swing.JButton();
        Valider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        gauche.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("choisissez la taille du jeu");
        gauche.add(jLabel2, java.awt.BorderLayout.NORTH);

        jPanel5.setLayout(new java.awt.GridLayout(4, 1));

        buttonGroup1.add(enfant);
        enfant.setSelected(true);
        enfant.setText("enfant (8 cartes)");
        enfant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enfantActionPerformed(evt);
            }
        });
        jPanel5.add(enfant);

        buttonGroup1.add(debutant);
        debutant.setText("débutant (20 cartes)");
        debutant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debutantActionPerformed(evt);
            }
        });
        jPanel5.add(debutant);

        buttonGroup1.add(avance);
        avance.setText("avancé (36 cartes)");
        avance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avanceActionPerformed(evt);
            }
        });
        jPanel5.add(avance);

        buttonGroup1.add(expert);
        expert.setText("expert (64 cartes)");
        expert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expertActionPerformed(evt);
            }
        });
        jPanel5.add(expert);

        gauche.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(gauche);

        droite.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("choisissez les joueurs crées par défaut");
        droite.add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel4.setLayout(new java.awt.GridLayout(4, 1));

        lara.setText("Lara");
        lara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laraActionPerformed(evt);
            }
        });
        jPanel4.add(lara);

        jack.setText("Jack");
        jack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jackActionPerformed(evt);
            }
        });
        jPanel4.add(jack);

        jean.setText("Jean-Sébastien");
        jean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeanActionPerformed(evt);
            }
        });
        jPanel4.add(jean);

        amadeus.setText("Amadeus");
        amadeus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amadeusActionPerformed(evt);
            }
        });
        jPanel4.add(amadeus);

        droite.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel1.add(droite);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        Edition.setEditable(false);
        Edition.setColumns(20);
        Edition.setRows(5);
        jScrollPane1.setViewportView(Edition);

        jPanel2.add(jScrollPane1);
        jPanel2.add(BPhoto);

        getContentPane().add(jPanel2, java.awt.BorderLayout.EAST);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        jPanel3.add(Annuler);

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        jPanel3.add(Valider);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        //Si une des cases est sélectionné, crée une instance de type Joueur avec le nom et la famille préférée du joueur puis ajouter sa photo à la liste des joueurs
        if (lara.isSelected())
        {
            Joueur a = new Joueur ("Lara", "epique");
            a.setPhoto(new ImageIcon(getClass().getResource("/img/lara.jpg")));
            this.lj.ajouteJoueur(a);
        }
          
        
        if (jack.isSelected())
        {
            Joueur a = new Joueur ("Jack", "rares");
            a.setPhoto(new ImageIcon(getClass().getResource("/img/jack.png")));
            this.lj.ajouteJoueur(a);
        }
        
        if (jean.isSelected())
        {
            Joueur a = new Joueur ("Jean-Sebastien", "alpines-femmes");
            a.setPhoto(new ImageIcon(getClass().getResource("/img/bach.jpg")));
            this.lj.ajouteJoueur(a);
        }
        
        if (amadeus.isSelected())
        {
            Joueur a = new Joueur ("Amadeus", "communs");
            a.setPhoto(new ImageIcon(getClass().getResource("/img/anonyme.png")));
            this.lj.ajouteJoueur(a);
        }
            
        
        
        this.ok=true;
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_ValiderActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        // annuler et fermer l'application
        
        this.ok = false;
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_AnnulerActionPerformed

    private void debutantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debutantActionPerformed
        // choix du niveau de jeu en mode debutant
        this.nc = 10;
    }//GEN-LAST:event_debutantActionPerformed

    private void enfantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enfantActionPerformed
        // choix du niveau de jeu en mode enfant
        this.nc = 4 ;
    }//GEN-LAST:event_enfantActionPerformed

    private void avanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avanceActionPerformed
        // choix du niveau de jeu avancé
        this.nc = 18;
    }//GEN-LAST:event_avanceActionPerformed

    private void expertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expertActionPerformed
        // choix du niveau de jeu en mode expert
        this.nc = 32 ;
    }//GEN-LAST:event_expertActionPerformed

    private void laraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laraActionPerformed
        // lara
        Joueur a = new Joueur ("Lara" , "épiques"); //instance de type joueur avec le nom et la famille en parametre
        a.setPhoto (new ImageIcon(getClass().getResource("/img/lara.jpg"))); // ajout de la photo
        Edition.setText( a.toString()); // affichage des informations (nom et famille) sur la zone d'édition
        Image img = a.getPhoto().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH);
        BPhoto.setIcon( new ImageIcon(img));
    }//GEN-LAST:event_laraActionPerformed

    private void jackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jackActionPerformed
        // jack 
        Joueur a = new Joueur ("Jack" , "rares"); //instance de type joueur avec le nom et la famille en parametre
        a.setPhoto (new ImageIcon(getClass().getResource("/img/jack.png"))); // ajout de la photo
        Edition.setText( a.toString());  // affichage des informations (nom et famille) sur la zone d'édition
        Image img = a.getPhoto().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH);
        BPhoto.setIcon( new ImageIcon(img));
    }//GEN-LAST:event_jackActionPerformed

    private void jeanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeanActionPerformed
        // jean sebastien
        Joueur a = new Joueur ("Jean-Sébastien" , "alpins-femmes"); //instance de type joueur avec le nom et la famille en parametre
        a.setPhoto (new ImageIcon(getClass().getResource("/img/bach.jpg"))); // ajout de la photo
        Edition.setText( a.toString()); // affichage des informations (nom et famille) sur la zone d'édition
        Image img = a.getPhoto().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH);
        BPhoto.setIcon( new ImageIcon(img));
    }//GEN-LAST:event_jeanActionPerformed

    private void amadeusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amadeusActionPerformed
        // amadeus
        Joueur a = new Joueur ("Amadeus" , "communs");  //instance de type joueur avec le nom et la famille en parametre
        a.setPhoto (new ImageIcon(getClass().getResource("/img/anonyme.png"))); // ajout de la photo
        Edition.setText( a.toString()); // affichage des informations (nom et famille) sur la zone d'édition
        Image img = a.getPhoto().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH);
        BPhoto.setIcon( new ImageIcon(img));
    }//GEN-LAST:event_amadeusActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JButton BPhoto;
    private javax.swing.JTextArea Edition;
    private javax.swing.JButton Valider;
    private javax.swing.JCheckBox amadeus;
    private javax.swing.JRadioButton avance;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton debutant;
    private javax.swing.JPanel droite;
    private javax.swing.JRadioButton enfant;
    private javax.swing.JRadioButton expert;
    private javax.swing.JPanel gauche;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jack;
    private javax.swing.JCheckBox jean;
    private javax.swing.JCheckBox lara;
    // End of variables declaration//GEN-END:variables
}
