/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.*;
import javax.swing.*;
import java.io.* ;
/**
 *
 * @author DIALLO Mamoudou 
 */
public class SaisieJoueurDlg extends javax.swing.JDialog {

    //attributs
    private ImageIcon photo;
    private LesPersonnages lp;
    private boolean fermeture;
    private Joueur nouveau_joueur;
    
    
    
    //Accesseurs en get
    public Joueur getNouveau_joueur()
    {
        return this.nouveau_joueur;
    }
    public boolean getFermeture()
    {
        return this.fermeture;
    }
    
    
    //Methode qui rempli la Jlist
    private void initListeFamilles()
    {
        DefaultListModel model= (DefaultListModel)ListeFamilles.getModel();
        ListeFamilles.setModel(model);
        for (int i=0; i<this.lp.getFamilles().size(); i++)
        {
            model.addElement(this.lp.getFamilles().get(i));
        }
    }
   
    
    //Constructeurs
    public SaisieJoueurDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public SaisieJoueurDlg(java.awt.Frame parent, boolean modal, LesPersonnages persos) {
        super(parent, modal);
        initComponents();
        this.lp = persos;
        DefaultListModel model= new DefaultListModel();
        ListeFamilles.setModel(model);
        initListeFamilles();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ListeFamilles = new javax.swing.JList<>();
        jPanel14 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Parcourir = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        Photo = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        Annuler = new javax.swing.JButton();
        Valider = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jPanel10.setLayout(new java.awt.GridLayout(3, 1));

        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel6.setText("Donnez votre pseudo:");
        jPanel12.add(jLabel6, java.awt.BorderLayout.NORTH);

        Edition.setColumns(20);
        Edition.setRows(5);
        jScrollPane3.setViewportView(Edition);

        jPanel12.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel12);

        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel7.setText("Quelle est votre famille préférée de personnage ?");
        jPanel13.add(jLabel7, java.awt.BorderLayout.NORTH);

        jScrollPane4.setViewportView(ListeFamilles);

        jPanel13.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel13);

        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel8.setText("Choisissez une photo:");
        jPanel14.add(jLabel8, java.awt.BorderLayout.NORTH);

        Parcourir.setText("Parcourir");
        Parcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParcourirActionPerformed(evt);
            }
        });
        jPanel14.add(Parcourir, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel14);

        jPanel1.add(jPanel10);

        jPanel11.setLayout(new java.awt.BorderLayout());
        jPanel11.add(Photo, java.awt.BorderLayout.CENTER);

        jPanel15.setLayout(new java.awt.GridLayout(1, 2));

        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        jPanel15.add(Annuler);

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        jPanel15.add(Valider);

        jPanel11.add(jPanel15, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanel11);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabel5.setText("Créez votre joueur !");
        jPanel9.add(jLabel5);

        getContentPane().add(jPanel9, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ParcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParcourirActionPerformed
        // l'ouverture du gestionnaire de fichier lors du clic sur ce  bouton
        JFileChooser jf= new JFileChooser();
        if (jf.showOpenDialog(this)== JFileChooser.APPROVE_OPTION)
    {
        String path = jf.getSelectedFile().getPath();
        Image img=Toolkit.getDefaultToolkit().getImage(path);
        img=img.getScaledInstance(Photo.getWidth()-10, Photo.getHeight()-10, Image.SCALE_DEFAULT);
        photo = new ImageIcon(img);
        Photo.setIcon(photo);
    }
    }//GEN-LAST:event_ParcourirActionPerformed

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        // verifie si la famille est bien selectionné et pseudo rempli avant de valider
        String p;
        int i=ListeFamilles.getSelectedIndex();
        if(!Edition.getText().equals("")&&i!=-1){
            String f=ListeFamilles.getSelectedValue().toString();
            p=Edition.getText();
            this.nouveau_joueur =new Joueur(p,f);
            if(photo!=null){
                nouveau_joueur.setPhoto(photo);
            }
            this.fermeture=true;
            this.setVisible(false);
        }
        else{
            Edition.setText("Le pseudo est vide, veuillez le remplir"); //message d'erreur si le pseudo est vide
            this.fermeture=false;
            this.setVisible(true);
        }
    }//GEN-LAST:event_ValiderActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        // annuler et fermer la boite
        this.fermeture=false;
        this.setVisible(false);
    }//GEN-LAST:event_AnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SaisieJoueurDlg dialog = new SaisieJoueurDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JTextArea Edition;
    private javax.swing.JList<String> ListeFamilles;
    private javax.swing.JButton Parcourir;
    private javax.swing.JButton Photo;
    private javax.swing.JButton Valider;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
