/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author DIALLO Mamoudou 
 */
public class VisuJoueursDlg extends javax.swing.JDialog {

    //Attributs
    private LesJoueurs lj;

    //Constructeur
    public VisuJoueursDlg(java.awt.Frame parent, boolean modal, LesJoueurs lstj) {
        super(parent, modal);
        initComponents();
        this.lj = lstj; // récupération du paramètre (lstj) dans l’attribut lj.
        initTrombi();
    }
    
    //Methode pour gerer l'affichage des joueurs séléctionner dans l'application principale au sein de la boite de dialogue
    public void initTrombi()
    {
        int nb = this.lj.getNbJoueurs();
        Panneau.setLayout(new GridLayout(1, nb));
        for (int i=0; i<nb; i++)
        {
            JButton jb= new JButton();
            Joueur j= lj.getJoueur(i);
            jb.setName(""+i);
            jb.addActionListener(new java.awt.event.ActionListener(){
                public void actionPerformed(java.awt.event.ActionEvent evt){
                    AfficheInfosJoueur(evt);
                }
                        
            });
            Panneau.add(jb);
        }
        this.pack(); // pour ajuster correctement la taille des composants après les ajouts si besoin
    }
    
    //Methode pour afficher les infos du joueur lors du clic sur sa photo
    public void AfficheInfosJoueur(java.awt.event.ActionEvent evt)
    {
        JButton jb= (JButton)evt.getSource();
        int n=Integer.parseInt(jb.getName());
        Joueur a= this.lj.getJoueur(n);
        Edition.setText(a.toString());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Panneau = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();
        Afficher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Choisissez un joueur pour voir ses caractéristiques");
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);
        getContentPane().add(Panneau, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        Edition.setEditable(false);
        Edition.setColumns(20);
        Edition.setRows(5);
        jScrollPane1.setViewportView(Edition);

        jPanel1.add(jScrollPane1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.EAST);

        Afficher.setText("Afficher");
        Afficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfficherActionPerformed(evt);
            }
        });
        getContentPane().add(Afficher, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfficherActionPerformed
        // 
        for (int i=0; i<this.lj.getNbJoueurs(); i++) //boucle pour parcourir la liste des joueurs
        {
            JButton jb= (JButton)Panneau.getComponent(i); // recuperation du button crée par la methode init Panneau
            Joueur a= this.lj.getJoueur(i); //recupere le joueur d'indice i
            Image img = a.getPhoto().getImage().getScaledInstance(jb.getWidth(), jb.getHeight(), Image.SCALE_SMOOTH);
            jb.setIcon(new ImageIcon(img));
        }
    }//GEN-LAST:event_AfficherActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Afficher;
    private javax.swing.JTextArea Edition;
    private javax.swing.JPanel Panneau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}