/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author DIALLO Mamoudou 
 */
public class VisuPersonnagesDlg extends javax.swing.JDialog {
    //Attributs
    private Joueur jr;
    

   //Constructeurs
    public VisuPersonnagesDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public VisuPersonnagesDlg(java.awt.Frame parent, boolean modal, Joueur j) {
        super(parent, modal);
        initComponents();
        this.jr= j;
        initPanneau();
    }
    
   /* //Methode pour afficher les cartes gagnées encours du jeu
    private void initPanneau()
    {
        int nb = this.jr.getPaquet().getTaille();
        Panneau.setLayout(new GridLayout(nb-1, nb-1));
        for (int i=0; i<nb; i++)
        {
            JButton jb= new JButton();
            Personnage a= jr.getPaquet().getPerso(i);
            jb.setName(""+i);
            Panneau.add(jb);
        }
        this.pack(); // pour ajuster correctement la taille des composants après les ajouts si besoin
    */
    public  void initPanneau()
    {   
        LesPersonnages lc = this.jr.getPaquet();
        int nbi= lc.getTaille();
        // taille de la grille nxn
        int n= (int) Math.floor(Math.sqrt(nbi))+1; 
        Panneau.setLayout(new java.awt.GridLayout(n, n));
        for (int i =0; i<nbi; i++)
        { 
            JButton bt= new JButton();
            Panneau.add(bt);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Panneau = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Afficher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Cartes du joueur :");
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        Panneau.setLayout(new java.awt.GridLayout(2, 2));
        getContentPane().add(Panneau, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        jLabel2.setText("Score :");
        jPanel2.add(jLabel2);

        Afficher.setText("Afficher");
        Afficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfficherActionPerformed(evt);
            }
        });
        jPanel2.add(Afficher);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfficherActionPerformed
        // TODO add your handling code here:
        for (int i=0; i<this.jr.getPaquet().getTaille(); i++) //boucle pour parcourir la liste des joueurs
        {
            JButton jb= (JButton)Panneau.getComponent(i); // recuperation du button crée par la methode init Panneau
            Personnage a= this.jr.getPaquet().getPerso(i); //recupere le joueur d'indice i
            Image img = a.getPhoto().getScaledInstance(jb.getWidth(), jb.getHeight(), Image.SCALE_SMOOTH);
            jb.setIcon(new ImageIcon(img));
            jLabel2.setText("Score : " + this.jr.getScore());
            jLabel1.setText("Carte du joueur : " +this.jr.getPseudo());
        }
    }//GEN-LAST:event_AfficherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisuPersonnagesDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisuPersonnagesDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisuPersonnagesDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisuPersonnagesDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VisuPersonnagesDlg dialog = new VisuPersonnagesDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Afficher;
    private javax.swing.JPanel Panneau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
